version: '3'
services:
  auth:
    image: auth:latest

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
  
  mongo:
    image: mongo:latest